### ISSUE TITLE
Dropping packages: Gnu stack and more

### ISSUE THREAD

**Issue by a-schaefers** [kisslinux/community#1165]
It has been fun, but life and work is getting the way of being able to maintain this, so first come first serve. Open a PR adding a space to the end of the 'version' file to claim your package(s), and reply here so I can cross off the list.

~bc~
~coreutils~
~dash~
~diffutils~
~ed~
~emacs
emacs-git
emacs-nox~
expect
findutils
~gawk~
gnu-netcat
~gnugrep~
~gnupg2~
~gnutls~
~gtar
iproute2
iptables
iputils
kmod~
libassuan
~libcap~
~libgcrypt
libgpg-error~
libksba
~libxaw3d~
~lzip~
~lzo
mksh
nawk-git~
~nettle~
npth
~openvpn~
~patch~
~pciutils~
pinentry
~pkcs11-helper~
~procps-ng~
~readline~
~sed~
shadow
~strace~
~wget~

**Comment by dilyn-corner** [comment]
I'll probably take a couple; some of these are needed for KISS-kde. I'll take a closer look later.

**Comment by magenbluten** [comment]
i have interest / need the following packages and could take over maintenance:

- mksh
- iproute2
- openvpn
- iptables
- strace
- maybe: iputils
- maybe: sed

**Comment by periish** [comment]
I'll take lzip, readline, ed, dash, bc, patch, gnugrep,  and gnupg2.

**Comment by periish** [comment]
Update: #1167 is my PR.

**Comment by a-schaefers** [comment]
> i have interest / need the following packages and could take over maintenance:
> 
> * mksh
> * iproute2
> * openvpn
> * iptables
> * strace
> * maybe: iputils
> * maybe: sed

Open a PR claiming them as yours or I can't cross them off the list.

**Comment by cemkeylan** [comment]
Wow, I am seeing we are having a buffet once again! I would like to order

- Coreutils
- Emacs* and dependencies
- gnutls and dependencies
- libxaw3d
- wget

**Comment by cemkeylan** [comment]
Okay, here is the full list of packages I have taken:

- coreutils
- diffutils
- emacs*
- gawk
- gnutls
- libxaw3d
- nettle
- pciutils
- procps-ng
- wget

**Comment by a-schaefers** [comment]
Thanks @periish and @cemkeylan , list updated.

**Comment by dilyn-corner** [comment]
@periish might also want to talk `libassuan`, `libgcrypt`, and `libgpg-error` (all are required by `gnupg2`). 
@aicsx or @mmatongo might want `libcap`. 
Otherwise, I'll take the aforementioned.

**Comment by mmatongo** [comment]
I'll take lipcap

**Comment by periish** [comment]
Will you fix #1150?

**Comment by mmatongo** [comment]
> Will you fix #1150?

Let me get on it now

**Comment by onodera-punpun** [comment]
I can take:

* libgcrypt
* libgpg-error
* lzo

**Comment by dylanaraps** [comment]
lzo has already been adopted. @onodera-punpun 

See: https://github.com/kisslinux/community/pull/1174/files

**Comment by a-schaefers** [comment]
#1174 thank you @magenbluten

**Comment by a-schaefers** [comment]
Thank you also @onodera-punpun & @mmatongo 

list updated

**Comment by dylanaraps** [comment]
Last orphans:

```
  expect
  findutils
  gnu-netcat
  libassuan
  npth
  shadow
  pinentry
```

@periish libassuan, npth and pinentry are around solely for gnupg2 which is one of your packages, care to adopt these?

I will adopt the remainder of the packages.

**Comment by periish** [comment]
I shall do so soon

**Comment by Vouivre** [comment]
Which packages will you adopt @dylanaraps  ? npth, libassuan and pinentry ? 

I didn't want to adopt these, because I don't use them, I know only pinentry. But it seems they are pretty easy to maintain. So I could adopt them, so you will have more time to improve KISS :wink: . What do you think ? 

If you agree, I will do the change next week.

**Comment by dylanaraps** [comment]
@Vouivre All packages have been adopted if periish takes over npth, libassuan and pinentry.

**Comment by Vouivre** [comment]
Next time I will read the whole comment.....

Ok, I'll wait for the confirmation.

**Comment by dylanaraps** [comment]
@periish Any update? (You also have four outdated packages: https://repology.org/projects/?maintainer=58531601%2Bperiish%40users.noreply.github.com&outdated=1)

**Comment by cemkeylan** [comment]
@periish @dylanaraps I can take the `gnupg2` stack since I am already maintaining those at home as well. If you would want that, of course.

**Comment by dylanaraps** [comment]
@cemkeylan npth, libassuan and pinentry are yours. gnupg2 maintainership depends on @periish though I'm really leaning towards just giving it to you. It has been out-of-date since August 27 ([2.2.22](https://lists.gnupg.org/pipermail/gnupg-announce/2020q3/000447.html), [2.2.23](https://lists.gnupg.org/pipermail/gnupg-announce/2020q3/000448.html)) and seeing as it is security focused (and one of the releases is a security fix)... I'm sure everyone can understand. 

You know what @cemkeylan? They're all yours. I want to close this issue, #1224 and #1225, they've been open long enough. 


@periish While on the topic of outdated stuff, another reminder for NSS which hasn't been updated since July 24 ([3.55](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_3.55_release_notes), [3.56](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_3.56_release_notes)). Update is of arguable importance as it's used by qt5-webengine for certificate stuff. Let me know if you don't have the time (or if there are any technical issues delaying update, etc) and I'll take over maintenance short term (or long term). Am happy to do this, just let me know (same goes for any other outdated packages you have). :)
