### ISSUE TITLE
msmtp: use LibreSSL instead of GnuTLS

### ISSUE THREAD

**Issue by noocsharp** [kisslinux/community#1525]
msmtp has support for LibreSSL by specifying `--with-tls=openssl` when running configure. I think it makes mores sense to use LibreSSL as it is in the official repo, and therefore an extra library is not required.

@Vouivre

**Comment by Vouivre** [comment]
I have to investigate if it makes more sense. For sure, it's better to use `libressl` because it's in the official repo. I have removed the `gnutls` dependency and `libressl` is detected as `openssl` which is discouraged. I have no idea if the dev of `msmtp` will remove the support of `openssl` and in that case also the support of `libressl`. I will contact him to know what he thinks about it. 
By the way, `gnutls` is recommended here:

https://marlam.de/msmtp/news/openssl-discouraged/

By the way, voidlinux based on `libressl` use `gnutls` for `msmtp`.

**Comment by Vouivre** [comment]
In short: I won't change for `libressl`. See https://github.com/marlam/msmtp-mirror/issues/37.

Ok for you @dylanaraps ? As the dev ok KISS, perhaps you have another opinion.
