### ISSUE TITLE
(Hopefully temporary) fork for keeping packages up to date

### ISSUE THREAD

**Issue by CamilleScholtz** [kisslinux/community#1656]
Since @dylanaraps seems to be gone, forks have been created to keep the packages up to date, the most active one seems to be https://github.com/kiss-community/repo-community

Personally I think it would be nice if maintainers still create a PR here and the maintainers of `repo-community` then merge it in their repo, rather than sending PR's directly to the `repo-community`, so this repo could easily be made up to date once Dylan is back and so we wont get two diverging repositories.

Thoughts? This issue is for general discussion about forks and what to do without repo maintainer.

**Comment by CamilleScholtz** [comment]
As for in the future, maybe a backup maintainer would be nice.

**Comment by Vouivre** [comment]
Thank you for this information. Probably because I'm not on IRC, I didn't know about this fork. 

I have created three new PR, but only in this repo. I don't know what has to be done to take a PR from this repo and to apply it on https://github.com/kiss-community/repo-community. If it's not too much work, I think it's a good solution. 

To follow the new releases it is very practical with repology. For now it's not necessary, but depending how long this temporary solution will be used, perhaps this new repo should be added to repology. 

I'm also from the opinion to have a second maintainer as backup. I really hope it's a temporary solution. Something similar happened with voidlinux and the new maintainers had to create a new website and new repo on github. I hope we will have some news from @dylanaraps soon.

**Comment by git-bruh** [comment]
@Vouivre you just need to go to the forked repo's page, create PR and then select your fork and it's branch (eg msmtp)

https://github.com/kiss-community/repo-community/compare/main...vouivre:msmtp

**Comment by Vouivre** [comment]
Thank you, but it doesn't work. I get: "There isn't anything to compare". Do I have to fork the repo "kiss-community" ? It seems you didn't fork it. Here is what I have done:

https://github.com/kiss-community/repo-community/compare/master...Vouivre:youtube-dl

If I create a PR on kiss-community, the web interface change directly on kisslinux/community. Why ?

**Comment by git-bruh** [comment]
> There isn't anything to compare

this is because you're trying to compare with the `master` branch which doesn't exist, it's `main` by default on new repos

Also, there's a conflict because your closed PR (#1618) was merged already

**Comment by Vouivre** [comment]
Ok, I was not very smart here, I didn't see `main` instead of `master`, sorry. 

If we take the example of `youtube-dl`,  a new PR can't be merge because of PR https://github.com/kisslinux/community/pull/1618 which has already been merged. If I understand correctly, I have to fork the repo https://github.com/kiss-community/repo-community and create a PR on my fork. Right ? Or the conflict doesn't matter, and it's not a problem to solve it. I think the best is the first solution. Right ?

**Comment by git-bruh** [comment]
Use your existing fork
```
git remote add kiss-community https://github.com/kiss-community/repo-community.git
git fetch kiss-community
git checkout -b ytdl kiss-community/main
# Update youtube-dl
git push origin
```
Then compare and PR at https://github.com/kiss-community/repo-community/compare/main...vouivre:ytdl

**Comment by Vouivre** [comment]
Thank you!
