### ISSUE TITLE
pinetree-dmenu version incorrect(?)

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/community#250]
@cemkeylan 

https://repology.org/projects/?inrepo=kiss_community&outdated=1

**Comment by cemkeylan** [comment]
Since this is my own implementation, I versioned it accordingly. AFAIK there are three more implementations of pinentry-dmenu. I am familiar with two. One of them is just a basic script, the latter requires unnecessary dependencies and is error-prone.
 I could rename the implementation if it would be better.

**Comment by dylanaraps** [comment]
I'll contact the repology guy and see what we can do.
