### ISSUE TITLE
sinit: dependency on ubase requires kiss alternatives intervention

### ISSUE THREAD

**Issue by a-schaefers** [kisslinux/community#273]
Currently sinit requires respawn (currently of the ubase package) to keep your getty alive (busybox init uses inittab to accomplish this).

While we were at it, [building the sinit package], to kill two birds with one stone, the included sinit scripts also default to using ubase-box getty. I consider this a nice touch.

The problem is that this was all devised before the new alternatives system became available. We have since upgraded ubase-box to take advantage of alternatives, which however requires manual intervention to install.

How do we address this?

**Comment by dylanaraps** [comment]
1. I'd bundle `respawn` with `sinit` so that `sinit` works regardless of which `coreutils` is installed. It doesn't matter if this conflicts with `ubase` as the alternatives system will cover this. This should prevent breakage with the new `ubase-box` install method.

2.  Include a message in the `post-install` script explaining the need for manual intervention. I will also write a news post on the website and a post on the subreddit for maximum exposure. You can direct users to the man page for `kiss` once I push it.

3. The sinit scripts should probably use whatever getty is available on the system. It can look for `ubase` getty first if you like before falling back to other gettys.

**Comment by cemkeylan** [comment]
Busybox comes as the default, and ubase does conflict with a lot of tools. I think the getty should be added for busybox by default. We could also add a commented getty for ubase on the init scripts.

So instead of trying to detect which getty is installed on the boot scripts, we could just leave it to the user.

```sh
# For busybox getty
sinit_run_getty() {
    for getty in 1 2 3 4 5 6 ; do
        respawn /sbin/getty 34800 "tty${getty}" 2>&1 &
    done
}

# For ubase getty
# sinit_run_getty() {
#     for getty in 1 2 3 4 5 6 ; do
#         respawn /sbin/getty "/dev/tty${getty}" linux 2>&1 &
#     done
# }
```

I am currently informing the user that sinit uses busybox getty by default, and they have to manually change it if they are planning on using ubase getty

**Comment by dylanaraps** [comment]
I like this solution. :+1:

**Comment by a-schaefers** [comment]
I'd like us to consider this idea https://github.com/kisslinux/community/pull/276#issuecomment-580157966
