### ISSUE TITLE
Package request: ripgrep

### ISSUE THREAD

**Issue by Jackojc** [kisslinux/community#5]
Moved from old repo. (https://github.com/kisslinux/repo/issues/17)

**Comment by dylanaraps** [comment]
This can be installed through `cargo`.

**Comment by Jackojc** [comment]
Isn't the point of a central package manager that you shouldn't have to involve extra tools like this? Surely requiring the user to go through more effort for this is against KISS philosophy.

**Comment by dylanaraps** [comment]
Nothing stops you as a user from packaging this software in your own repository which can then be shared with other users. A KISS package for this would be a repeat of the `cargo` commands required to install it regardless.

I see it as far less simple to package something already available in its "own" package manager (`cargo`). This involves using `cargo` through an abstraction (`kiss`) and further involves somebody to maintain the package and all of its dependencies all the way down the chain.

Exceptions are to be made of course (*see `cbindgen` and `python-mako`*) but I see it as wrong to eventually end up mirroring the PyPi or Crate repositories which again involves people to put in the work to keep them up to date.

User repositories are no different from the "official" ones and if someone wants to put in this work and go this route, they can! User repositories can be shared exactly like this one and even repository signing can be used.

**Comment by konimex** [comment]
I have to agree with @Jackojc here.

Multiple package managers managing a single installation can lead into a mess. Packages managed by `kiss` can conflict with packages managed by `cargo` (or `pip`, or whatever else). For *user-only* packages (i.e. no `sudo` so only in `$HOME/bin`) or even `/usr/local`, I'd agree. But anything in `/usr` should be managed by one package manager only.

It'd be no different to stuff like `pip` or even `npm`.

`community` should be open to any and all packages, **as long as someone want to maintain the package**.

**Comment by Jackojc** [comment]
Yeah I think it being in the community repo should be fine. I understand your points @dylanaraps but who is KISS meant to be simple for? the user or maintainer?

**Comment by dylanaraps** [comment]
I was talking solely about packages installed to `$HOME` and **not** the system. I agree that only `kiss` should be used for system-wide package management of course. I thought I made this obvious(?), I guess not!

> I understand your points @dylanaraps but who is KISS meant to be simple for? the user or maintainer?

I don't think it's so black and white. I desire for KISS to be simple in its implementation, the amount of software used and the software choices made. This further extends to the distribution being simple to understand on all levels.

This can mean things are simpler on the developer side, user side, both sides or even no sides.

Reducing the maintenance burden on the project overall (*where possible!*) is another one of my goals. This just so happens to also align with my goals for simplicity mentioned above. 

This comes from:

- Having a small and simple base system (*it has actually shrunken in size over time*).
- Having small and curated repositories (*the less packages to maintain means more time spent per package on the developer side*).
- Having less code (*code is weight and I believe in the more code is equal to more bugs philosophy*).
- Having less abstractions (*the less unique distribution specific tooling needed the better*).
- Avoiding feature-creep (*this involves saying **no** sometimes*).

These also extend to reducing the financial burden of the project and further extend to reducing the development time of the project. My time is limited and I'm doing this for free (*because I love it!*) but there *are* limits.

Others may disagree with any of the above which is why I've designed the package management around the user. Users can create their own repositories, share them with others or even keep them to themselves.

User repositories are no different from the "official" ones and repository signature verification can also be used in exactly the same way. I intend for users to create their own repositories and share them with others.

KISS will stay maintainable solely by myself and will act as a simple, solid, up-to-date and reliable base. It is not my intention for KISS to eventually become similar in scope to Arch, Void, Alpine etc but to remain small with infinite possibilities for extension by users.

Believe it or not but most Linux distributions are either having or will end up having issues regarding maintenance of their projects overall. Dive into the mailing lists and you'll find threads on what I'm talking about.

It has always been my goal to avoid this at all costs.

---

**Regarding language package managers**

I need to think even further about the best course of action regarding the packaging of software from Pypi, Npm, Crates.io and other programming language "distribution channels".

I don't believe the right solution is packaging everything under the sun (*from them*), however nor do I yet have an alternative solution in mind. I've seen what has happened to other distributions in this regard and I don't want a repeat to occur here.

For some time now I've had ideas brewing in my head for community which are indirectly related to this issue and I'll incorporate them into my thoughts on this topic.

I'll continue thinking about this, I appreciate your concerns and I thank you for bringing them up. An alternative view point is always welcome.

**Comment by konimex** [comment]
Since we're talking about `community` here, I think we need to separate it from the main `repo` repo.

>KISS will stay maintainable solely by myself and will act as a simple, solid, up-to-date and reliable base.

Yes, and I think you should limit the scope of reliable base to `repo` (i.e. you don't have to maintain `community` packages at all if you're not the primary maintainer. If repology shows an outdated package, just mention the maintainer, and if one doesn't show up in, say, 30 days, then delete the package from `community` (or give breathing room if someone else wants to maintain it). Of course, this is what I've been thinking, but the policy is up to you).

-------------------

>I don't believe the right solution is packaging everything under the sun (from them), however nor do I yet have an alternative solution in mind.

Packaging "everything" will not (and should not) happen given the nature of `community` (let alone `repo`).

> however nor do I yet have an alternative solution in mind.

For packages that can be managed by `pip`, `setup.py` exists, thus it's possible to avoid `pip` entirely (e.g. pywal). However, within rust and node (good thing we don't have any `npm` packages), things get tricky since `cargo` and `node` double as package manager *and* build system. So yeah, it'll be tough to find an alternative.

> I've seen what has happened to other distributions in this regard and I don't want a repeat to occur here.

Can you elaborate?
