### ISSUE TITLE
Json-c different manifest since swap to cmake

### ISSUE THREAD

**Issue by sdsddsd1** [kisslinux/community#505]
@konimex since swapped to cmake for json-c some files are missing. That are:
`libjson-c.so.4.0.0` `libjson-c.so.4`  `libjson-c.la`. `json_visit.h` `json_object_iterator.h` .
Kiss-manifest for json-c with gnu-make:
```
/usr/lib/pkgconfig/json-c.pc
/usr/lib/pkgconfig/
/usr/lib/libjson-c.so.4.0.0
/usr/lib/libjson-c.so.4
/usr/lib/libjson-c.so
/usr/lib/libjson-c.la
/usr/lib/libjson-c.a
/usr/lib/
/usr/include/json-c/printbuf.h
/usr/include/json-c/linkhash.h
/usr/include/json-c/json_visit.h
/usr/include/json-c/json_util.h
/usr/include/json-c/json_tokener.h
/usr/include/json-c/json_pointer.h
/usr/include/json-c/json_object_iterator.h
/usr/include/json-c/json_object.h
/usr/include/json-c/json_inttypes.h
/usr/include/json-c/json_config.h
/usr/include/json-c/json_c_version.h
/usr/include/json-c/json.h
/usr/include/json-c/debug.h
/usr/include/json-c/bits.h
/usr/include/json-c/arraylist.h
/usr/include/json-c/
/usr/include/
/usr/
```
Are you in particular need of cmake for wyvertux? If so I can provide this package myself.
Greetings.

**Comment by konimex** [comment]
Of course the SONAME is missing, this is becoming common on CMake-based build systems for some packages. Anyway, `.la` is generally unneeded on modern Linux systems. But I'll need to take a look for the headers.

The reason I swapped to cmake is to prevent `automake` systems. And since commit https://github.com/json-c/json-c/commit/a92e6d2c2840c88b8a4a3a2520b71c7b4a63e018 a patch should be available. I'll take a look tomorrow.

>Are you in particular need of cmake for wyvertux?

`cryptsetup` needs it (for KISS though, Wyvertux is on hold for the time being as I'm focused on Wyverkiss) so I need it for my franken-KISS' eldritch monster system.

**Comment by konimex** [comment]
Looking at the changes made (particularly for CMake) since last release, I guess the only way forward is to go "latest commit" (though I'm not tracking `git` since I believe the changes are pretty trivial from my view) until a new version is finally released. I'll get a PR ready tomorrow.
