### ISSUE TITLE
sic-git:  style guide violation + package naming convention concern

### ISSUE THREAD

**Issue by mcpcpc** [kisslinux/community#812]
1. Per KISS Style Guide 1403, package should refer to the tarball and not the git repository (where possible).
2. There are no KISS rules on package naming conventions (as far as i can tell), but the "*-git" in the package name is confusing.  Considering `kiss search` only handles exact package names at the moment, I would advise renaming the package from "sic-git" to "sic".

reference: https://k1ss.org/style

**Comment by dylanaraps** [comment]
> Per KISS Style Guide 1403, package should refer to the tarball and not the git repository (where possible).

Some packages may be better served as `-git` ones and their sources will reflect this. It's all up to the maintainer of the package. Nothing prevents someone from submitting a `sic` package which tracks releases. There is typically a rationale attached to the package submission (for `sic-git`, see: https://github.com/kisslinux/community/pull/233).

> There are no KISS rules on package naming conventions (as far as i can tell), but the "*-git" in the package name is confusing. Considering kiss search only handles exact package names at the moment, I would advise renaming the package from "sic-git" to "sic".

The `-git` in the name follows `-bin` (for binary packages). It's intentional and within reason. Also, `kiss search` supports globbing (`kiss s 'pkg*'`). I agree that the documentation here is lacking regarding this information. I'll get onto fixing this.

**Comment by dylanaraps** [comment]
I've updated the style guide to contain this information. :+1:
