### ISSUE TITLE
Qemu out of date

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/community#95]
@jdavies-dev 

See: https://repology.org/projects/?inrepo=kiss_community&outdated=1

**Comment by jdavies-dev** [comment]
I don't think qemu is out of date.  From their front page (https://www.qemu.org/), the latest release is 4.1.1.   There is a 4.2.0 branch, but this is not yet released (still at rc4).

Repology thinks that the latest version of qemu is 4.1.93, which is why it's saying our package is out of date.  However, this is not a real qemu version number - I think it's something invented by OpenSUSE.

Take a look at the other distro's versions of qemu:
https://repology.org/project/qemu/versions

You can see that the only people with "4.1.93" are OpenSUSE.  And if you look at the OpenSUSE build file for this package, you can see that they are actually using 4.2.0-rc3, but calling it 4.1.93:

https://build.opensuse.org/package/view_file/openSUSE:Factory/qemu/qemu.spec?expand=1

So I think that we are OK.

**Comment by dylanaraps** [comment]
Thanks, I'll forward this to the Repology dev.

**Comment by dylanaraps** [comment]
Fixed in Repology. Thanks again. :+1:
